import { ContentStatus, PrismaClient, Role, StreamType } from '../src/generated/prisma/client';
import * as bcrypt from 'bcryptjs';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
const pool = new Pool({ connectionString: process.env.DATABASE_URL || 'postgresql://kinotv:kinotv_dev_password@localhost:5432/kinotv?schema=public' });
const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });
const movieCategories = [
  ['O‘zbek kinolari','🇺🇿'],['Rus kinolari','🇷🇺'],['Xorijiy kinolar','🌍'],['Jangari','🔥'],['Romantik','❤️'],['Komediya','😂'],['Drama','🎭'],['Fantastika','🚀'],['Qo‘rqinchli','👻'],['Detektiv','🕵️'],['Sarguzasht','🏃'],['Oilaviy','👨‍👩‍👧'],['Multfilm','👶'],['Seriallar','📺'],
];
const tvCategories = [['O‘zbekiston','🇺🇿'],['Rossiya','🇷🇺'],['Xorijiy','🌍'],['Yangiliklar','📰'],['Sport','⚽'],['Musiqa','🎵'],['Kino','🎬'],['Bolalar','👶'],['Ilm-fan','🔬'],['Biznes','💰'],['Ko‘ngilochar','🎭']];
const genreNames = ['Jangari','Romantik','Komediya','Drama','Fantastika','Qo‘rqinchli','Detektiv','Sarguzasht','Oilaviy','Animatsiya','Hujjatli film','Ilmiy-fantastika','Jinoyat','Triller','Biografik','Tarixiy'];
const slug = (s:string)=>s.toLowerCase().replace(/[‘’']/g,'').replace(/[^a-z0-9а-яёқғҳў]+/gi,'-').replace(/^-|-$/g,'');
async function main(){
  for(const [name,icon] of movieCategories) await prisma.movieCategory.upsert({where:{name},update:{icon},create:{name,icon,slug:slug(name),order:movieCategories.findIndex(x=>x[0]===name)}});
  for(const [name,icon] of tvCategories) await prisma.tVCategory.upsert({where:{name},update:{icon},create:{name,icon,slug:slug(name),order:tvCategories.findIndex(x=>x[0]===name)}});
  for(const name of genreNames) await prisma.genre.upsert({where:{name},update:{},create:{name,slug:slug(name)}});
  const admin = await prisma.user.upsert({where:{email:'admin@kinotv.uz'},update:{role:Role.ADMIN,isActive:true},create:{name:'KinoTV Admin',email:'admin@kinotv.uz',passwordHash:await bcrypt.hash('KinoTV_Admin_2026!',12),role:Role.ADMIN}});
  await prisma.admin.upsert({where:{userId:admin.id},update:{},create:{userId:admin.id,permissions:['*']}});
  await prisma.user.upsert({where:{email:'demo@kinotv.uz'},update:{},create:{name:'Demo foydalanuvchi',email:'demo@kinotv.uz',passwordHash:await bcrypt.hash('Demo_User_2026!',12)}});
  const movieCategoryRows=await prisma.movieCategory.findMany();
  const genreRows=await prisma.genre.findMany();
  const cat=(...names:string[])=>names.map(name=>movieCategoryRows.find(x=>x.name===name)!.id);
  const gen=(...names:string[])=>names.map(name=>genreRows.find(x=>x.name===name)!.id);
  await prisma.movie.deleteMany({where:{slug:{in:['big-buck-bunny-demo','elephants-dream-demo','sintel-demo','tears-of-steel-demo']}}});
  const movies=[
    {slug:'the-shawshank-redemption-1994',title:'The Shawshank Redemption',originalTitle:'The Shawshank Redemption',description:'Nohaq umrbod qamoq jazosiga hukm qilingan bankir Endi Dyufreyn Shoushenk qamoqxonasida umidini yo‘qotmaydi va mahbus Red bilan mustahkam do‘stlik o‘rnatadi.',posterUrl:'https://image.tmdb.org/t/p/w780/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',bannerUrl:'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',releaseYear:1994,durationMinutes:142,rating:9.3,language:'Ingliz tili',country:'AQSh',videoUrl:null,trailerUrl:'https://www.youtube.com/watch?v=6hB3S9bIaco',isLicensedVideo:false,metadataSource:'IMDb/TMDB',externalId:'tt0111161',isFeatured:true,isPopular:true,categoryIds:cat('Xorijiy kinolar','Drama'),genreIds:gen('Drama'),actors:['Tim Robbins','Morgan Freeman','Bob Gunton','William Sadler'],directors:['Frank Darabont']},
    {slug:'the-dark-knight-2008',title:'The Dark Knight',originalTitle:'The Dark Knight',description:'Betmen, leytenant Jim Gordon va prokuror Harvi Dent Gothamdagi jinoyatchilikka qarshi kurashadi. Joker paydo bo‘lgach, ularning tamoyillari eng og‘ir sinovdan o‘tadi.',posterUrl:'https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg',bannerUrl:'https://image.tmdb.org/t/p/original/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',releaseYear:2008,durationMinutes:152,rating:9.1,language:'Ingliz tili',country:'AQSh',videoUrl:null,trailerUrl:'https://www.youtube.com/watch?v=EXeTwQWrcwY',isLicensedVideo:false,metadataSource:'IMDb/TMDB',externalId:'tt0468569',isFeatured:true,isPopular:true,categoryIds:cat('Xorijiy kinolar','Jangari','Detektiv'),genreIds:gen('Jangari','Jinoyat','Drama','Triller'),actors:['Christian Bale','Heath Ledger','Aaron Eckhart','Gary Oldman','Michael Caine','Morgan Freeman'],directors:['Christopher Nolan']},
    {slug:'inception-2010',title:'Inception',originalTitle:'Inception',description:'Dom Kobb odamlarning tushiga kirib, sirlarni o‘g‘irlaydigan mutaxassis. Unga uyiga qaytish imkonini beradigan, ammo deyarli imkonsiz bo‘lgan g‘oyani ongga joylashtirish vazifasi topshiriladi.',posterUrl:'https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',bannerUrl:'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',releaseYear:2010,durationMinutes:148,rating:8.8,language:'Ingliz tili',country:'AQSh',videoUrl:null,trailerUrl:'https://www.youtube.com/watch?v=YoHD9XEInc0',isLicensedVideo:false,metadataSource:'IMDb/TMDB',externalId:'tt1375666',isFeatured:true,isPopular:true,categoryIds:cat('Xorijiy kinolar','Fantastika','Jangari'),genreIds:gen('Ilmiy-fantastika','Jangari','Triller'),actors:['Leonardo DiCaprio','Joseph Gordon-Levitt','Elliot Page','Tom Hardy','Ken Watanabe','Marion Cotillard'],directors:['Christopher Nolan']},
    {slug:'interstellar-2014',title:'Interstellar',originalTitle:'Interstellar',description:'Yer yashash uchun yaroqsiz bo‘lib borayotgan bir paytda, sobiq uchuvchi Kuper insoniyat uchun yangi makon topish maqsadida fazodagi qurt teshigi orqali xavfli sayohatga chiqadi.',posterUrl:'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',bannerUrl:'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',releaseYear:2014,durationMinutes:169,rating:8.7,language:'Ingliz tili',country:'AQSh',videoUrl:null,trailerUrl:'https://www.youtube.com/watch?v=zSWdZVtXT7E',isLicensedVideo:false,metadataSource:'IMDb/TMDB',externalId:'tt0816692',isFeatured:true,isPopular:true,categoryIds:cat('Xorijiy kinolar','Fantastika','Sarguzasht'),genreIds:gen('Ilmiy-fantastika','Sarguzasht','Drama'),actors:['Matthew McConaughey','Anne Hathaway','Jessica Chastain','Michael Caine','Mackenzie Foy'],directors:['Christopher Nolan']},
    {slug:'parasite-2019',title:'Parasite',originalTitle:'Gisaengchung',description:'Qashshoq Kim oilasi badavlat Park oilasining uyiga birin-ketin ishga kiradi. Ularning puxta rejasi uy ostida yashiringan kutilmagan sir tufayli xavfli tus oladi.',posterUrl:'https://image.tmdb.org/t/p/w780/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',bannerUrl:'https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',releaseYear:2019,durationMinutes:132,rating:8.5,language:'Koreys tili',country:'Janubiy Koreya',videoUrl:null,trailerUrl:'https://www.youtube.com/watch?v=5xH0HfJHsaY',isLicensedVideo:false,metadataSource:'IMDb/TMDB',externalId:'tt6751668',isFeatured:true,isPopular:true,categoryIds:cat('Xorijiy kinolar','Drama','Komediya','Detektiv'),genreIds:gen('Drama','Komediya','Triller'),actors:['Song Kang-ho','Lee Sun-kyun','Cho Yeo-jeong','Choi Woo-shik','Park So-dam'],directors:['Bong Joon Ho']},
    {slug:'oppenheimer-2023',title:'Oppenheimer',originalTitle:'Oppenheimer',description:'Fizik J. Robert Oppenheimerning Manxetten loyihasiga rahbarlik qilishi, atom bombasining yaratilishi va keyinchalik uning siyosiy hamda axloqiy oqibatlari bilan yuzlashishi haqidagi biografik drama.',posterUrl:'https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',bannerUrl:'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',releaseYear:2023,durationMinutes:181,rating:8.2,language:'Ingliz tili',country:'AQSh',videoUrl:null,trailerUrl:'https://www.youtube.com/watch?v=uYPbbksJxIg',isLicensedVideo:false,metadataSource:'IMDb/TMDB',externalId:'tt15398776',isFeatured:true,isPopular:true,categoryIds:cat('Xorijiy kinolar','Drama'),genreIds:gen('Biografik','Tarixiy','Drama'),actors:['Cillian Murphy','Emily Blunt','Matt Damon','Robert Downey Jr.','Florence Pugh'],directors:['Christopher Nolan']},
  ];
  for(const movie of movies){const {categoryIds,genreIds,actors,directors,...data}=movie;await prisma.movie.upsert({where:{slug:movie.slug},update:{...data,status:ContentStatus.ACTIVE,categories:{set:categoryIds.map(id=>({id}))},genres:{set:genreIds.map(id=>({id}))},actors:{set:[],connectOrCreate:actors.map(name=>({where:{name},create:{name}}))},directors:{set:[],connectOrCreate:directors.map(name=>({where:{name},create:{name}}))}},create:{...data,status:ContentStatus.ACTIVE,categories:{connect:categoryIds.map(id=>({id}))},genres:{connect:genreIds.map(id=>({id}))},actors:{connectOrCreate:actors.map(name=>({where:{name},create:{name}}))},directors:{connectOrCreate:directors.map(name=>({where:{name},create:{name}}))}}});}
  const entertainment=await prisma.tVCategory.findUniqueOrThrow({where:{name:'Ko‘ngilochar'}}), abroad=await prisma.tVCategory.findUniqueOrThrow({where:{name:'Xorijiy'}}), science=await prisma.tVCategory.findUniqueOrThrow({where:{name:'Ilm-fan'}});
  const channels=[
    {slug:'kinotv-demo-live',name:'KinoTV Demo Live',logoUrl:'https://placehold.co/300x300/6d28d9/ffffff.png?text=KinoTV',bannerUrl:'https://placehold.co/1280x720/111827/ffffff.png?text=KinoTV+Demo+Live',description:'HLS ijrosini tekshirish uchun ommaviy test oqimi. Haqiqiy telekanal emas.',country:'Demo',language:'Ingliz tili',streamUrl:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',streamType:StreamType.HLS,isPopular:true,order:1,categoryIds:[entertainment.id,abroad.id]},
    {slug:'kinotv-science-demo',name:'KinoTV Ilm-fan Demo',logoUrl:'https://placehold.co/300x300/0891b2/ffffff.png?text=ILM',bannerUrl:'https://placehold.co/1280x720/083344/ffffff.png?text=Ilm-fan+Demo',description:'Ilm-fan kategoriyasi uchun qonuniy sintetik demo kanal.',country:'Demo',language:'O‘zbek tili',streamUrl:'https://test-streams.mux.dev/test_001/stream.m3u8',streamType:StreamType.HLS,isPopular:false,order:2,categoryIds:[science.id]},
  ];
  for(const c of channels){const {categoryIds,...data}=c;await prisma.tVChannel.upsert({where:{slug:c.slug},update:{...data,status:ContentStatus.ACTIVE,categories:{set:categoryIds.map(id=>({id}))}},create:{...data,status:ContentStatus.ACTIVE,categories:{connect:categoryIds.map(id=>({id}))}}});}
  const demoChannel=await prisma.tVChannel.findUniqueOrThrow({where:{slug:'kinotv-demo-live'}});
  await prisma.tVProgram.deleteMany({where:{channelId:demoChannel.id,startsAt:{gte:new Date(Date.now()-86400000)}}});
  const start=new Date();start.setMinutes(0,0,0);
  const names=['Tonggi dastur','Kino yangiliklari','Ochiq film namoyishi','Texnologiya olami','Kechki dastur','Eng yaxshi lavhalar'];
  for(let i=-2;i<12;i++){const startsAt=new Date(start.getTime()+i*3600000),endsAt=new Date(startsAt.getTime()+3600000);await prisma.tVProgram.create({data:{channelId:demoChannel.id,title:names[(i+12)%names.length],description:'KinoTV qonuniy demo dastur jadvali.',startsAt,endsAt}})}
  console.log('Haqiqiy kino katalogi va qonuniy demo TV ma’lumotlari yaratildi. Admin: admin@kinotv.uz / KinoTV_Admin_2026!');
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(async()=>{await prisma.$disconnect();await pool.end()});
