'use client';

import { api, qs } from '@/lib/api';
import { useEffect, useState } from 'react';
import { Eye, Search, Trash2, UserCheck, UserX, X } from 'lucide-react';
import { toast } from 'sonner';
import { fmt, Loading, PageHeader, Status } from '@/components/ui';

export default function Users() {
  const [data,setData]=useState<any>(),[q,setQ]=useState(''),[page,setPage]=useState(1),[role,setRole]=useState(''),[selected,setSelected]=useState<any>();
  const load=()=>api(`/admin/users?${qs({q,page,limit:20,role})}`).then(setData).catch((e)=>toast.error(e.message));
  useEffect(()=>{void load();},[q,page,role]);
  async function patch(id:string,body:any){try{await api(`/admin/users/${id}`,{method:'PATCH',body:JSON.stringify(body)});toast.success("Foydalanuvchi yangilandi");load();}catch(e){toast.error((e as Error).message)}}
  async function detail(id:string){try{setSelected(await api(`/admin/users/${id}`));}catch(e){toast.error((e as Error).message)}}
  async function remove(id:string){if(!confirm("Bu foydalanuvchini haqiqatan ham o‘chirmoqchimisiz?"))return;try{await api(`/admin/users/${id}`,{method:'DELETE'});toast.success("Foydalanuvchi o‘chirildi");load();}catch(e){toast.error((e as Error).message)}}
  return <><PageHeader title="Foydalanuvchilar va admin rollari" description="Hisoblar, bloklash va SUPER ADMIN / ADMIN / MODERATOR huquqlarini boshqaring"/>
    <div className="card mb-5 flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-zinc-600" size={18}/><input className="input pl-10" placeholder="Ism, email yoki telefon…" value={q} onChange={(e)=>{setQ(e.target.value);setPage(1)}}/></div><select className="input sm:w-52" value={role} onChange={(e)=>setRole(e.target.value)}><option value="">Barcha hisoblar</option><option value="USER">Foydalanuvchilar</option><option value="ADMIN">Adminlar</option></select></div>
    {!data?<Loading/>:<><div className="table-wrap"><table className="table"><thead><tr><th>Foydalanuvchi</th><th>Rol</th><th>Ko‘rishlar</th><th>Ro‘yxatdan o‘tgan</th><th>Holat</th><th>Amallar</th></tr></thead><tbody>{data.data.map((u:any)=><tr key={u.id}><td><div className="flex min-w-52 items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-brand-500/10 font-bold text-brand-400">{u.name[0]}</span><div><p className="font-medium text-white">{u.name}</p><p className="text-xs text-zinc-600">{u.email||u.phone}</p></div></div></td><td><select className="rounded-lg border border-line bg-ink px-2 py-1.5 text-xs" value={u.role==='USER'?'USER':u.adminRole||'ADMIN'} onChange={(e)=>void patch(u.id,e.target.value==='USER'?{role:'USER'}:{adminRole:e.target.value})}><option value="USER">USER</option><option value="SUPER_ADMIN">SUPER ADMIN</option><option value="ADMIN">ADMIN</option><option value="MODERATOR">MODERATOR</option></select></td><td>{fmt((u._count?.movieViews||0)+(u._count?.channelViews||0))}</td><td>{new Date(u.createdAt).toLocaleDateString('uz-UZ')}</td><td><Status value={u.isActive}/></td><td><div className="flex gap-1"><button title="Ko‘rish" className="btn-secondary px-3" onClick={()=>void detail(u.id)}><Eye size={16}/></button><button title={u.isActive?'Bloklash':'Blokdan chiqarish'} className={u.isActive?'btn-danger px-3':'btn-secondary px-3'} onClick={()=>void patch(u.id,{isActive:!u.isActive})}>{u.isActive?<UserX size={16}/>:<UserCheck size={16}/>}</button><button title="O‘chirish" className="btn-danger px-3" onClick={()=>void remove(u.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div><div className="mt-4 flex items-center justify-between text-sm text-zinc-500"><span>Jami {fmt(data.meta.total)} hisob</span><div className="flex gap-2"><button className="btn-secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Oldingi</button><button className="btn-secondary" disabled={!data.meta.hasNext} onClick={()=>setPage(page+1)}>Keyingi</button></div></div></>}
    {selected&&<UserModal user={selected} close={()=>setSelected(null)}/>}</>;
}
function UserModal({user,close}:{user:any;close:()=>void}){const counts=user._count||{};return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/80 p-4"><div className="card w-full max-w-xl p-6"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold">{user.name}</h2><p className="text-sm text-zinc-500">{user.email||user.phone}</p></div><button className="btn-secondary px-3" onClick={close}><X size={17}/></button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[['Rol',user.adminRole||user.role],['Kino ko‘rishlari',counts.movieViews],['Kanal ko‘rishlari',counts.channelViews],['Kino sevimlilari',counts.movieFavorites],['Kanal sevimlilari',counts.channelFavorites],['Tarix',counts.watchHistory]].map(([l,v])=><div className="rounded-xl bg-white/[.03] p-3" key={String(l)}><p className="text-xs text-zinc-500">{l}</p><p className="mt-1 font-semibold">{fmt(v)}</p></div>)}</div><p className="mt-5 text-xs text-zinc-600">Parollar xavfsizlik sababli admin panelda hech qachon ko‘rsatilmaydi.</p></div></div>}
