import 'package:flutter_riverpod/flutter_riverpod.dart';import '../../core/error/app_exception.dart';import '../../core/network/api_client.dart';import '../../core/network/token_storage.dart';import '../../data/models/models.dart';import '../../data/repositories/api_repositories.dart';import '../../domain/repositories/auth_repository.dart';import '../../domain/repositories/content_repository.dart';
final tokenStorageProvider=Provider((_)=>TokenStorage());final apiClientProvider=Provider((r)=>ApiClient(r.read(tokenStorageProvider)));final authRepositoryProvider=Provider<AuthRepository>((r)=>AuthRepositoryImpl(r.read(apiClientProvider),r.read(tokenStorageProvider)));final contentRepositoryProvider=Provider<ContentRepository>((r)=>ContentRepositoryImpl(r.read(apiClientProvider)));
class AuthState{final UserModel?user;final bool loading;final String?error;const AuthState({this.user,this.loading=false,this.error});bool get authenticated=>user!=null;}
class AuthNotifier extends StateNotifier<AuthState>{final AuthRepository repo;AuthNotifier(this.repo):super(const AuthState(loading:true)){restore();}Future<void>restore()async{try{state=AuthState(user:await repo.restore());}catch(e){state=AuthState(error:friendlyError(e));}}Future<bool>login(String id,String password)async{return _run(()=>repo.login(id,password));}Future<bool>register(String name,String id,String password)async{return _run(()=>repo.register(name,id,password));}Future<bool>_run(Future<UserModel>Function()work)async{state=AuthState(user:state.user,loading:true);try{state=AuthState(user:await work());return true;}catch(e){state=AuthState(error:friendlyError(e));return false;}}Future<void>logout()async{await repo.logout();state=const AuthState();}Future<void>updateSettings(Map<String,dynamic>data)async{try{state=AuthState(user:await repo.settings(data));}catch(e){state=AuthState(user:state.user,error:friendlyError(e));}}}
final authProvider=StateNotifierProvider<AuthNotifier,AuthState>((r)=>AuthNotifier(r.read(authRepositoryProvider)));
final homeProvider=FutureProvider((r)=>r.read(contentRepositoryProvider).home());final movieProvider=FutureProvider.family<MovieModel,String>((r,id)=>r.read(contentRepositoryProvider).movie(id));final channelProvider=FutureProvider.family<ChannelModel,String>((r,id)=>r.read(contentRepositoryProvider).channel(id));final programsProvider=FutureProvider.family<List<ProgramModel>,String>((r,id)=>r.read(contentRepositoryProvider).programs(id));final searchProvider=FutureProvider.autoDispose.family<Map<String,List<dynamic>>,String>((r,q)=>q.trim().length<2?{'movies':[],'channels':[]}:r.read(contentRepositoryProvider).search(q));final favoritesProvider=FutureProvider((r)=>r.read(contentRepositoryProvider).favorites());final historyProvider=FutureProvider((r)=>r.read(contentRepositoryProvider).history());
class PagedMovies{final List<MovieModel>items;final int page;final bool hasNext,loading;final String?error;const PagedMovies({this.items=const[],this.page=0,this.hasNext=true,this.loading=false,this.error});}
class MoviesNotifier extends StateNotifier<PagedMovies>{final ContentRepository repo;String?category;String sort='newest';MoviesNotifier(this.repo):super(const PagedMovies()){load();}Future<void>load({bool reset=false,String?categoryId,String?sortBy})async{if(state.loading||(!reset&&!state.hasNext))return;if(categoryId!=null)category=categoryId;if(sortBy!=null)sort=sortBy;if(reset)state=const PagedMovies();state=PagedMovies(items:state.items,page:state.page,hasNext:state.hasNext,loading:true);try{final p=await repo.movies(page:state.page+1,category:category,sort:sort);state=PagedMovies(items:[...state.items,...p.data],page:p.page,hasNext:p.hasNext);}catch(e){state=PagedMovies(items:state.items,page:state.page,hasNext:state.hasNext,error:friendlyError(e));}}}
final moviesProvider=StateNotifierProvider<MoviesNotifier,PagedMovies>((r)=>MoviesNotifier(r.read(contentRepositoryProvider)));
class ChannelsNotifier extends StateNotifier<({List<ChannelModel>items,int page,bool hasNext,bool loading,String?error})>{final ContentRepository repo;String?category;ChannelsNotifier(this.repo):super((items:[],page:0,hasNext:true,loading:false,error:null)){load();}Future<void>load({bool reset=false,String?categoryId})async{if(state.loading||(!reset&&!state.hasNext))return;if(categoryId!=null)category=categoryId;if(reset)state=(items:[],page:0,hasNext:true,loading:false,error:null);state=(items:state.items,page:state.page,hasNext:state.hasNext,loading:true,error:null);try{final p=await repo.channels(page:state.page+1,category:category);state=(items:[...state.items,...p.data],page:p.page,hasNext:p.hasNext,loading:false,error:null);}catch(e){state=(items:state.items,page:state.page,hasNext:state.hasNext,loading:false,error:friendlyError(e));}}}
final channelsProvider=StateNotifierProvider<ChannelsNotifier,({List<ChannelModel>items,int page,bool hasNext,bool loading,String?error})>((r)=>ChannelsNotifier(r.read(contentRepositoryProvider)));
